name: Release Nuget on GitHub Packages

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build
        run: dotnet build --configuration Release

      - name: Get version information from tag
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Package
        run: >
          dotnet pack --no-restore --no-build --configuration Release 
          -p:PackageVersion=${{ steps.get_version.outputs.version-without-v }} --output .

      - name: Publish
        run: >
          dotnet nuget push AliceProject.AnovSyntax.${{ steps.get_version.outputs.version-without-v }}.nupkg 
          -s https://nuget.pkg.github.com/AliceNovel/index.json 
          -k ${{ secrets.NUGET_AUTH_TOKEN }}
